
camera:
    id: 0 #/dev/video0
    fovh: 75 # fov horizontal 
    w: 5120 # capture pixel width
    h: 800 # capture height
    c: 3 # BGR
    pformat: BA81
    wr: 2560 # resized target width

marker:
    cameraids: [0,1,2,3] # do marker det only on camera [0-3]
    family: 36h11
    size: 0.18 # marker side in meters
    ids: [1,2,3,4,5,6,7,8] # ids to keep

objdet:
    cameraids: [0,1,2,3] # do object det only on camera [0-3]

stream:
    camid: 0 # default camera
    ip: 192.168.1.50
    port: 5000

tasks: # what tasks to run
    marker: True
    objdet: True
    stream: True

display: # process to display images
    main: False
    marker: True
    objdet: True

FPS: # FPS display settings
    org: [5, 20]
    fontscale: 0.5
    color: [0,255,255]
    thickness: 1

