camera_id: 0

# Marker size is 6.5 inches by 6.5 inches
# https://firstfrc.blob.core.windows.net/frc2024/FieldAssets/2024FieldDrawings.pdf
# the left and right from the robots point of view

marker_ids: 
  - 1 # Blue drop off right side across from blue home
  - 2 # Blue drop off left side across from blue home
  - 3 # Red speaker right side 
  - 4 # Red speaker left side
  - 5 # Red amp
  - 6 # Blue amp
  - 7 # Blue speaker right side
  - 8 # Blue speaker left side
  - 9 # Red drop off right side
  - 10 # Red drop off left side
  # Looking from red home POV
  - 11 # Left red stage
  - 12 # Right red stage
  - 13 # Middle red stage
  # Looking from blue home POV
  - 14 # Middle blue stage
  - 15 # Left blue stage
  - 16 # Right blue stage

fovh: 70
width: 1280
height: 720
marker_family: 36h11
marker_size: 0.1651 # Each marker side in meters
